import React from "react";
import ReverseButton from "../../Components/ButtonsFolder/ReverseButton/ReverseButton.jsx";
import NotRobot from "../../Components/NotRobotFolder/NotRobot.jsx";
import "./LocalArtist.css";
// import PeaceFlower from "./peace-flower.svg";
// import SparkleStar from "./sparkle-star.svg";
// import GroovyHeart from "./groovy-heart.svg";
import { useEffect } from "react";



const LocalArtistFolder = () => {
  useEffect(() => {
  window.scrollTo(0, 0);
}, []);
  return (
    <div className="local-artist-wrapper">
       < ReverseButton />
      
      {/* Floating Hippie Objects */}
      {/* <img src={PeaceFlower} className="float peace-flower" alt="Peace Flower" />
      <img src={SparkleStar} className="float sparkle-star" alt="Sparkle Star" />
      <img src={GroovyHeart} className="float groovy-heart" alt="Groovy Heart" /> */}

      {/* Main Content */}
      <div className="content-box">
         <div className="NotRobotGradient h-[100px] w-[100px] m-auto mb-2  ">< NotRobot /></div>
        <h1 className="groovy-title  whitespace-nowrap mb-4 
              ">
          🧑🏼‍🎨 Support Your Local Artist 🎨
        </h1>

               

        <p className="groovy-text text-center">
          Our hippie community believes in 
          <strong>human hands, real hearts, and real creativity</strong>.
        </p>
        
        <p className="groovy-text">
          Digital art has been around for decades — long before AI — and it`s a legit art form
          created by real humans. On this site, everything you see is either:
        </p>

        <ul className="groovy-list">
          <li>🌼 Handmade art and illustration</li>
          <li>📸 Real photography shot by human eyes</li>
          <li>🖌️ Illustrator artwork and hand‑crafted vectors</li>
          <li>🔷 Custom SVGs drawn with intention, not generated by a bot</li>
          <li>🍄 Crafty magic from real artists</li>
          <li>✨ Photoshop for the digital artist</li>
          <li>✨ Custom Written CSS Animations</li>
        </ul>

        <p className="groovy-text">
          We honor the artists who pour their soul into their work—whether they use cameras,
          pencils, tablets, or vector tools.  
          This page is your reminder: <strong>Love your local creators</strong>.  
          Buy their art. Share their work. Keep the vibe alive.
        </p>

        <div className="badge">
          💛 Made by Human Hands 💛
        </div>
      </div>
    </div>
  );
};

export default LocalArtistFolder;
