import React, { useEffect } from "react";
import ReverseButton from "../../Components/ButtonsFolder/ReverseButton/ReverseButton.jsx";
import NotRobot from "../../Components/NotRobotFolder/NotRobot.jsx";
import BatSignal from "../../Components/ContactMeFolder/ContactMe.jsx";
import Weed from "../../Images/The_Stitching_Stoner/favicon.png";
import "./LocalArtist.css";

const LocalArtistFolder = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="local-artist-wrapper ">

      {/* HEADER */}
      <header className="local-artist-header relative">

        {/* Home Link */}
        <a href="/" className="home-link">
          <img
            src={Weed}
            className="absolute left-8 top-8 scale-[175%] z-50"
            alt="Return to Home"
          />
        </a>

        {/* Reverse Button */}
        <ReverseButton />

        {/* No Zone Badge */}
        <div className="NotRobotGradient relative m-auto mb-2 mt-4 h-[100px] w-[100px]">
          <span className="not-robot noZone">No Zone</span>
          <NotRobot />
        </div>
      </header>

      {/* MAIN CONTENT */}
      <main className="relative content-box mt-8">

        <h1 className="groovy-title mb-4 whitespace-nowrap">
          🧑🏼‍🎨 Support Your Local Artist 🎨
        </h1>

        <p className="groovy-text text-center">
          A Hippie community believes in
          <strong> human hands, real hearts, and real creativity</strong>.
        </p>

        <p className="groovy-text">
          Digital art has been around for decades — long before AI — and it’s a
          legit art form created by real humans. On this site, everything you
          see is either:
        </p>

        <ul className="groovy-list">
          <li>🌼 Handmade art and illustration</li>
          <li>📸 Real photography shot by human eyes</li>
          <li>🖌️ Illustrator artwork and hand‑crafted vectors</li>
          <li>🔷 Custom SVGs drawn with intention, not generated by a bot</li>
          <li>🍄 Crafty magic from real artists</li>
          <li>✨ Photoshop for the digital artist</li>
          <li>✨ Custom Written CSS Animations</li>
        </ul>

        <p className="groovy-text">
          We honor the artists who pour their soul into their work—whether they
          use cameras, pencils, tablets, or vector tools. This page is your
          reminder: <strong>Love your local creators</strong>. Buy their art.
          Share their work. Keep the vibe alive.
        </p>
      </main>

      {/* CONTACT ASIDE */}
      <aside className="contact-aside relative">
        <span className="absolute right-4 bottom-[-.5rem]  z-50">
          <BatSignal />
        </span>
      </aside>

      {/* FOOTER */}
      <footer className="badge relative text-amber-200">
        💛 Made by Human Hands 💛
      </footer>

    </div>
  );
};

export default LocalArtistFolder;
